<div class="page-body">
    <!-- Container-fluid starts-->
    <div class="container-fluid m-t-20">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header pb-0">
                        <h4 class="card-title mb-0">Consultores</h4>
                    </div>
                    <div class="card-body">
                        <form id="filter" autocomplete="off">
                            <div class="row">
                                <div class="col-md-3">
                                    <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                                class="fa fa-plus"></i> Consultor</a>
                                </div>
                                <div class="col-md-3 my-auto">
                                    <div class="form-group">
                                        <input class="form-control" id="nameFilter" name="name" type="text"
                                               placeholder="Nome">
                                    </div>
                                </div>
                                <div class="col-md-3 my-auto">
                                    <div class="form-group">
                                        <select class="form-control form-select" id="typeFilter" name="type">
                                            <option value="0">Selecionar</option>
                                            <option value="2">Admin</option>
                                            <option value="3">Convencional</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col text-end">
                                    <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar
                                    </button>
                                    <button class="btn btn-primary" type="submit">Buscar</button>
                                </div>
                            </div>
                        </form>
                        <div class="row">
                            <div class="col">
                                <p>Exibindo <span id="partial"></span> de <span id="total"></span></p>
                            </div>
                        </div>
                        <div class="row table-responsive-lg">
                            <div class="col">
                                <table class="table table-hover table-sm" id="usersTable" width="100%"
                                       cellspacing="0">
                                    <thead>
                                    <tr>
                                        <th>Nome</th>
                                        <th class="text-center">E-mail</th>
                                        <th class="text-center">Tipo</th>
                                        <th class="text-center">Status</th>
                                        <th class="text-center">Ações</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col text-center">
                                <div class="spinner-border loaderTable" role="status">
                                    <span class="sr-only mx-auto">Loading...</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="addUser" method="post" autocomplete="off">
                <div class="modal-header">
                    <h5 class="modal-title">Registro de Consultor</h5>
                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="row mt-3">
                    <div class="col text-center">
                        <div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
                            <span class="sr-only mx-auto">Loading...</span>
                        </div>
                    </div>
                </div>
                <div class="modal-body form-group">
                    <input type="hidden" name="userId" id="userId">
                    <div class="row">
                        <div class="col">
                            <label for="name">Nome</label>
                            <input id="name" name="name" placeholder="Nome" type="text" class="form-control">
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-8">
                            <label for="email">E-mail</label>
                            <input id="email" name="email" placeholder="E-mail" type="email"
                                   class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="type">E-mail</label>
                            <select id="type" name="type" class="form-control form-select">
                                <option value="">Selecionar</option>
                                <option value="2">Admin</option>
                                <option value="3">Convencional</option>
                            </select>
                        </div>
                    </div>
                    <div class="row" id="passwordDiv">
                        <div class="col-md-6">
                            <label for="password">Senha</label>
                            <input id="password" name="password" placeholder="Senha" type="password"
                                   class="form-control">
                            <span style="font-size: 10px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                        </div>
                        <div class="col-md-6">
                            <label for="password2">Confirme a Senha</label>
                            <input id="password2" name="password2" placeholder="Confirme a Senha"
                                   type="password" class="form-control">
                            <span style="font-size: 10px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="row" style="width: 100%;">
                        <div class="col" style="width: 100%">
                            <span style="bottom: 10px; position: fixed; z-index: 8888; width: 95%; text-align: center; display: none"
                                  class="alert alert-danger" role="alert" id="messageUserRegister"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col text-end">
                            <button type="submit" class="btn btn-primary">Salvar Consultor</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script>

    var index = partial = name = type =0;
    var total = 1;

    const formAddUser = document.getElementById('addUser');

    function validateForm() {
        $('.form-control').removeClass('is-invalid is-valid');
        let errors = [];
        let ids = [];
        let radios = [];
        let greens = [];
        let classes = [];
        const formData = formDataToJson('addUser');

        if (formData.name.trim() == '') {
            errors.push('<b> Nome</b>');
            ids.push('name');
        } else {
            greens.push('name')
        }
        if (formData.email.trim() == '') {
            errors.push('<b> Email</b>');
            ids.push('email');
        } else {
            greens.push('email')
        }
        if (formData.type.trim() == '') {
            errors.push('<b> Tipo do Usuário</b>');
            ids.push('type');
        } else {
            greens.push('type')
        }
        if (formData.userId.trim() == 0 && formData.password.trim() == '') {
            errors.push('<b> Senha</b>');
            ids.push('password');
        } else {
            greens.push('password')
        }
        if (formData.userId.trim() == 0 && formData.password2.trim() == '') {
            errors.push('<b> Confirme a Senha</b>');
            ids.push('password2');
        } else {
            greens.push('password2')
        }

        for (let i = 0; i < greens.length; i++) {
            $('#' + greens[i]).addClass('is-valid')
        }

        if (formData.password.trim() != '' && formData.password2.trim() != '' && (formData.password.length < 8 || formData.password2.length < 8)) {
            showNotify('danger', 'As senhas devem ter no mínimo oito caracteres!', 1500);
            $('#password, #password2').addClass('is-invalid');
            return false;
        }

        if (formData.password.trim() != '' && formData.password2.trim() != '' && formData.password != formData.password2) {
            showNotify('danger', 'As senha estão diferentes!', 1500);
            $('#password, #password2').addClass('is-invalid');
            return false;
        }
        
        return verifyMessage(errors, ids, radios, classes);
    }

    function openModal() {
        $('.form-control').removeClass('is-invalid is-valid');
        document.getElementById('passwordDiv').style.display = 'block';
        document.getElementById('userId').value = 0;
        $('#modal').modal('show');
        document.getElementById('addUser').reset();
    }

    function openModalEdit(id) {
        $('.form-control').removeClass('is-invalid is-valid');
        document.getElementById('passwordDiv').style.display = 'none';
        document.getElementById('addUser').reset();
        $('#modal').modal('show');
        if (id > 0) {
            startLoading();
            fetch(`<?= BASEURL ?>usuarios/listar/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    setTimeout(function () {
                        $('.loaderTop').hide();
                        $('.form-group').css('opacity', 1);
                        $('.btn').attr('disabled', false);
                    }, 500);
                    document.getElementById('email').value = json.email;
                    document.getElementById('userId').value = json.id;
                    document.getElementById('type').value = json.type;
                    document.getElementById('name').value = json.name;
                });
            });
        }
    }

    formAddUser.addEventListener('submit', e => {
        e.preventDefault();
        startLoading();
        if (!validateForm()) {
            setTimeout(function () {
                $('.loaderTop').hide();
                $('.form-group').css('opacity', 1);
                $('.btn').attr('disabled', false);
            }, 500);
            return;
        }
        let formData = formDataToJson('addUser');
        fetch("<?= BASEURL ?>usuarios/registrar", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(formAddUser)
        }).then(response => {
            setTimeout(function () {
                $('.loaderTop').hide();
                $('.form-group').css('opacity', 1);
                $('.btn').attr('disabled', false);
            }, 500);
            response.json().then(json => {
                if (response.status === 200) {
                    formAddUser.reset();
                    showNotify('success', json.message, 2000);
                    setTimeout(function () {
                        $('#modal').modal('hide');
                        resetTable();
                    }, 2000);
                } else {
                    showNotify('danger', json.message, 2000);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        type = formData.type;
        $("#usersTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = partial = name = type = 0;
        total = 1;
        $("#usersTable tbody").empty();
        generateTable();
    }

    function generateUsersTable(user) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info pointer" title="Editar" onclick="openModalEdit(${user.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td>${user.name}</td>
                    <td class="text-center">${user.email}</td>
                    <td class="text-center">${typeStr(user.type)}</td>
                    <td class="text-center">${buttonStatus(user.active, user.id)}</td>
                    ${actions}
                </tr>`;
    }

    function buttonStatus(status, id) {
        if (status == 1) {
            return `
            <div class="badge badge-primary label-square" onclick="changeStatusUser(${id}, 0)">
                <span class="f-14">Ativo</span>
            </div>
            `;
        } else if (status == 0) {
            return `
            <div class="badge badge-danger label-square" onclick="changeStatusUser(${id}, 1)">
               <span class="f-14">Inativo</span>
            </div>
            `;
        }
    }

    function changeStatusUser(id, status) {
        fetch(`<?= BASEURL ?>usuarios/novo-status/?id=${id}&status=${status}`, {
            method: 'GET',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            response.json().then(json => {
                if (response.status === 200) {
                    showNotify('success', json.message, 2000);
                    setTimeout(function () {
                        resetTable();
                    }, 2000);
                } else {
                    showNotify('danger', json.message, 2000);
                }
            });
        });
    }

    function typeStr(type) {
        if (type == 2) {
            return 'Admin';
        } else if (type == 3) {
            return 'Convencional';
        } else {
            return 'Desconhecido';
        }
    }

    function generateTable() {
        if (total > partial) {
            $('.loaderTable').css('opacity', 1);
            fetch(`<?= BASEURL ?>usuarios/listar/?index=${index}&name=${name}&type=${type}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('.loaderTable').css('opacity', 0);
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    if (json.message.length > 0) {
                        let options = json.message.map(generateUsersTable);
                        $("#usersTable tbody").append(options);
                    } else {
                        $("#usersTable tbody").append(`<tr><td colspan="5" class="text-center">Nenhum resultado encontrado</td></tr>`);
                    }
                    if (json.message.length == 20) {
                        $("#usersTable tbody").append(`<tr id="btnEnvironment"><td colspan="5" class="text-center">
                                                            <a class="btn btn-block btn-primary w-100 f-12 btn-sm" onclick="addConsultants()">Ver Mais</a>
                                                  </td></tr>`);
                    }
                });
            });
        }
    }
    
    function addConsultants() {
        index++;
        generateTable();
    }

    $(document).ready(function () {
        generateTable();
        $("#password, #password2").bind('paste', function (e) {
            e.preventDefault();
        });
    });
</script>
