<div class="row mt-2">
    <div class="col">
        <div class="card p-3">
            <div class="row mt-3">
                <div class="col text-center">
                    <div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
                        <span class="sr-only mx-auto">Loading...</span>
                    </div>
                </div>
            </div>
            <form class="form-group" id="addCompany" method="post" autocomplete="off">
                <input type="hidden" name="companyId" id="companyId"
                       value="<?= $companySelected ? $companySelected->getId() : '' ?>">
                <div class="row">
                    <div class="col">
                        <h6 class="title" style="color: black">Informações da Empresa</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <label for="cnpj">CNPJ</label>
                        <input id="cnpj" name="cnpj" class="form-control" type="text" placeholder="CNPJ"
                               data-mask="99.999.999/9999-99"
                               value="<?= $companySelected ? $companySelected->getCnpj() : '' ?>">
                    </div>
                    <div class="col-sm-8">
                        <label for="nameEdit">Razão Social</label>
                        <input id="nameEdit" name="name" class="form-control" type="text" placeholder="Razão Social"
                               value="<?= $companySelected ? $companySelected->getName() : '' ?>">
                    </div>
                    <div class="col-sm-6">
                        <label for="socialReason">Nome Fantasia</label>
                        <input id="socialReason" name="socialReason" class="form-control" type="text"
                               placeholder="Nome Fantasia"
                               value="<?= $companySelected ? $companySelected->getSocialReason() : '' ?>">
                    </div>
                    <div class="col-sm-3">
                        <label for="cnae">CNAE Principal</label>
                        <input id="cnae" name="cnae" class="form-control" type="text" placeholder="CNAE Principal"
                               data-mask="99.99-9" value="<?= $companySelected ? $companySelected->getCnae() : '' ?>">
                    </div>
                    <div class="col-sm-3">
                        <label for="numbersOfWorkers">Qtd Trabalhadores</label>
                        <input id="numbersOfWorkers" name="numbersOfWorkers" class="form-control" type="number"
                               placeholder="Qtd Trabalhadores"
                               value="<?= $companySelected ? $companySelected->getNumbersOfWorkers() : '' ?>">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="zipCode">CEP</label>
                            <input class="form-control" name="zipCode" type="text" id="zipCode" placeholder="Cep"
                                   value="<?= $companySelected ? $companySelected->getZipCode() : '' ?>">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="state">Estado</label>
                            <input type="text" name="state" id="state" class="form-control" placeholder="UF"
                                   value="<?= $companySelected ? $companySelected->getState() : '' ?>">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="city">Cidade</label>
                            <input type="text" name="city" id="city" class="form-control" placeholder="Cidade"
                                   value="<?= $companySelected ? $companySelected->getCity() : '' ?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="neighborhood">Bairro</label>
                            <input type="text" name="neighborhood" id="neighborhood" class="form-control"
                                   placeholder="Bairro"
                                   value="<?= $companySelected ? $companySelected->getNeighborhood() : '' ?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="address">Logradouro</label>
                            <input type="text" name="address" id="address" class="form-control" placeholder="Endereço"
                                   value="<?= $companySelected ? $companySelected->getAddress() : '' ?>">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="number">Número</label>
                            <input type="text" name="number" id="number" class="form-control" placeholder="Número"
                                   value="<?= $companySelected ? $companySelected->getNumber() : '' ?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="complement">Complemento</label>
                            <input type="text" name="complement" id="complement" class="form-control"
                                   placeholder="Complemento"
                                   value="<?= $companySelected ? $companySelected->getComplement() : '' ?>">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mt-1">
                        <label for="contract">Logo da Empresa</label>
                        <span class="fileselector">
              <label class="btn btn-block btn-danger text-white" style="margin-top: 5px" for="logoCompany">
                  <input class="upload-file-selector" id="logoCompany" type="file" name="logoCompany">
                  <i class="fa fa-paperclip margin-correction"></i>
                      <span id="logoCompanyLabel" default="Anexar Arquivo">Anexar Arquivo</span>
              </label>
            </span>
                        <div class="galeria" id="logoCompanyImage"></div>
                    </div>
                    <div class="col-sm-3 mt-1">
                        <label for="contract">Cartão CNPJ</label>
                        <span class="fileselector">
              <label class="btn btn-block btn-danger text-white" style="margin-top: 5px" for="cardCnpj">
                  <input class="upload-file-selector" id="cardCnpj" type="file" name="cardCnpj">
                  <i class="fa fa-paperclip margin-correction"></i>
                      <span id="cardCnpjLabel" default="Anexar Arquivo">Anexar Arquivo</span>
              </label>
            </span>
                    </div>
                    <div class="col-sm-3 mt-4">
                        <a class="btn btn-secondary mt-3"
                           href="https://servicos.receita.fazenda.gov.br/servicos/cnpjreva/cnpjreva_solicitacao.asp"
                           target="_blank">
                            Consultar CNPJ
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <hr style="background-color: #002060">
                        <h6 class="title" style="color: black">Informações do Responsável</h6>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <label for="representative">Representante Legal</label>
                        <input name="representative" id="representative" class="form-control" type="text"
                               placeholder="Representante Legal"
                               value="<?= $companySelected ? $companySelected->getRepresentative() : '' ?>">
                    </div>
                    <div class="col-sm-4">
                        <label for="representativePosition">Cargo Representante Legal</label>
                        <select name="representativePosition" id="representativePosition" class="form-control form-select">
                            <option value="">Selecionar</option>
                            <option
                                    value="1" <?= $companySelected && $companySelected->getrepresentativePosition() == 1 ? 'selected' : '' ?>>
                                Proprietário
                            </option>
                            <option
                                    value="2" <?= $companySelected && $companySelected->getrepresentativePosition() == 2 ? 'selected' : '' ?>>
                                Presidente
                            </option>
                            <option
                                    value="3" <?= $companySelected && $companySelected->getrepresentativePosition() == 3 ? 'selected' : '' ?>>
                                Diretor Executivo
                            </option>
                            <option
                                    value="4" <?= $companySelected && $companySelected->getrepresentativePosition() == 4 ? 'selected' : '' ?>>
                                Diretor Geral
                            </option>
                            <option
                                    value="5" <?= $companySelected && $companySelected->getrepresentativePosition() == 5 ? 'selected' : '' ?>>
                                Chief Executive Officer - CEO
                            </option>
                            <option value="6" <?= $companySelected && $companySelected->getrepresentativePosition() == 6 ? 'selected' : '' ?>>
                                Gerente Geral
                            </option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <hr style="background-color: #002060">
                        <h6 class="title">Horário de Funcionamento</h6>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-4 text-center"><b>Início</b></div>
                    <div class="col-sm-6 text-center"><b>Intervalo</b></div>
                    <div class="col-sm-2 text-center"><b>Fim</b></div>
                </div>
                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Dom</b></span>
                        <input class="form-control" id="dom1" style="width: 40%" placeholder="HH:mm" data-mask="99:99"
                               value="<?= $hours && $hours->getDom1() ? $hours->getDom1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="dom2" style="width: 25%" placeholder="HH:mm" data-mask="99:99"
                               value="<?= $hours && $hours->getDom2() ? $hours->getDom2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="dom3" style="width: 25%" placeholder="HH:mm" data-mask="99:99"
                               value="<?= $hours && $hours->getDom3() ? $hours->getDom3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="dom4" style="width: 70%" placeholder="HH:mm" data-mask="99:99"
                               value="<?= $hours && $hours->getDom4() ? $hours->getDom4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>

                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Seg</b></span>
                        <input class="form-control" id="seg1" name="seg1" style="width: 40%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSeg1() ? $hours->getSeg1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="seg2" name="seg2" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSeg2() ? $hours->getSeg2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="seg3" name="seg3" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSeg3() ? $hours->getSeg3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="seg4" name="seg4" style="width: 70%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSeg4() ? $hours->getSeg4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>

                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Ter</b></span>
                        <input class="form-control" id="ter1" name="ter1" style="width: 40%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getTer1() ? $hours->getTer1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="ter2" name="ter2" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getTer2() ? $hours->getTer2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="ter3" name="ter3" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getTer3() ? $hours->getTer3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="ter4" name="ter4" style="width: 70%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getTer4() ? $hours->getTer4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>

                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Qua</b></span>
                        <input class="form-control" id="qua1" name="qua1" style="width: 40%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQua1() ? $hours->getQua1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="qua2" name="qua2" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQua2() ? $hours->getQua2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="qua3" name="qua3" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQua3() ? $hours->getQua3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="qua4" name="qua4" style="width: 70%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQua4() ? $hours->getQua4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>

                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Qui</b></span>
                        <input class="form-control" id="qui1" name="qui1" style="width: 40%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQui1() ? $hours->getQui1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="qui2" name="qui2" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQui2() ? $hours->getQui2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="qui3" name="qui3" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQui3() ? $hours->getQui3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="qui4" name="qui4" style="width: 70%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getQui4() ? $hours->getQui4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>

                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Sex</b></span>
                        <input class="form-control" id="sex1" name="sex1" style="width: 40%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSex1() ? $hours->getSex1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="sex2" name="sex2" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSex2() ? $hours->getSex2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="sex3" name="sex3" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSex3() ? $hours->getSex3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="sex4" name="sex4" style="width: 70%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSex4() ? $hours->getSex4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>

                <div class="row form-inline mt-2">
                    <div class="col-sm-4 text-center">
                        <span class="p-1"><b>Sáb</b></span>
                        <input class="form-control" id="sab1" name="sab1" style="width: 40%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSab1() ? $hours->getSab1()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-6 text-center">
                        <input class="form-control" id="sab2" name="sab2" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSab2() ? $hours->getSab2()->format('H:i') : '' ?>">
                        <span class="p-1">h às</span>
                        <input class="form-control" id="sab3" name="sab3" style="width: 25%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSab3() ? $hours->getSab3()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                    <div class="col-sm-2 text-center">
                        <input class="form-control" id="sab4" name="sab4" style="width: 70%" placeholder="HH:mm"
                               data-mask="99:99"
                               value="<?= $hours && $hours->getSab4() ? $hours->getSab4()->format('H:i') : '' ?>">
                        <span class="p-1">h</span>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col text-end">
                        <button type="submit" class="btn btn-primary">Salvar Empresa</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="<?= BASEURL ?>assets/functions/company.js?v=<?= time() ?>"></script>
