<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
          content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <title>GEind - Selecionar Empresa</title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/icofont.css?v=<?= time() ?>">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/themify.css?v=<?= time() ?>">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/flag-icon.css?v=<?= time() ?>">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/feather-icon.css?v=<?= time() ?>">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/animate.css?v=<?= time() ?>">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.css?v=<?= time() ?>">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>">
    <link id="color" rel="stylesheet" href="<?= BASEURL ?>assets/css/color-1.css?v=<?= time() ?>" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/responsive.css?v=<?= time() ?>">

    <script src="https://kit.fontawesome.com/b1f34ab4bc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/newStyle.css?v=<?= time() ?>">
</head>
<style>
    label {
        color: black;
        /*margin: 0;*/
    }


</style>
<body class="bg-light">
<div class="page-body">
    <div class="container-fluid m-t-50">
        <div class="container">
            <div class="card m-t-50 card-login mx-auto">
                <div class="text-center">
                    <h6 class=" my-auto text-center px-5 p-t-20 f-w-600" style="font-style: italic; color: grey">
                        Selecione uma empresa na
                        sua lista de clientes ou cadastre um novo cliente.</h6>
                </div>
                <hr style="background: #002060">
                <div class="card-body pb-4">
                    <form method="post" id="selectCompany">
                        <div class="form-group">
                            <label for="company">Empresa</label>
                            <select id="company" name="company" class="form-control form-select">
                                <option value="">Selecionar</option>
								<?php foreach ($companies as $company): ?>
                                    <option
                                            value="<?= $company->getId() ?>"><?= $company->getSocialReason() ? $company->getSocialReason() : $company->getSocialName() ?></option>
								<?php endforeach; ?>
								<?php if (!$companies): ?>
                                    <option value="">Você não possui empresas cadastradas</option>
								<?php endif; ?>
                            </select>
                            <div class="row">
                                <div class="col m-t-10 text-center">
                                    <button class="btn btn-primary btn-block m-t-5" type="submit">Selecionar</button>
									<?php if ($user->getType() == 2): ?>
                                        <a class="btn btn-secondary btn-block m-t-5" onclick="openModal()">Cadastrar</a>
									<?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="addCompany" method="post" autocomplete="off">
                <div class="modal-header">
                    <h5 class="modal-title" style="color: black">Registro de Empresa</h5>
                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="row mt-3">
                    <div class="col text-center">
                        <div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
                            <span class="sr-only mx-auto">Loading...</span>
                        </div>
                    </div>
                </div>
                <div class="modal-body form-group">
                    <div class="row">
                        <div class="col">
                            <h6 class="title" style="color: black">Informações da Empresa</h6>
                        </div>
                    </div>
                    <input type="hidden" name="companyId" id="companyId">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="cnpj">CNPJ *</label>
                            <input id="cnpj" name="cnpj" class="form-control" type="text" placeholder="CNPJ"
                                   data-mask="99.999.999/9999-99">
                        </div>
                        <div class="col-md-8">
                            <label for="socialReason">Nome Fantasia *</label>
                            <input id="socialReason" name="socialReason" class="form-control" type="text"
                                   placeholder="Nome Fantasia">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="nameEdit">Razão Social *</label>
                            <input id="nameEdit" name="name" class="form-control" type="text"
                                   placeholder="Razão Social" readonly>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="postage">Porte</label>
                            <input id="postage" name="postage" class="form-control" type="text" readonly
                                   placeholder="Porte">
                        </div>
                        <div class="col-md-4">
                            <label for="typeCompany">Tipo</label>
                            <input id="typeCompany" name="typeCompany" class="form-control" type="text" readonly
                                   placeholder="Tipo">
                        </div>
                        <div class="col-md-4">
                            <label for="situation">Situação</label>
                            <input id="situation" name="situation" class="form-control" type="text" readonly
                                   placeholder="Situação">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label for="cnae">CNAE Principal*</label>
                            <input id="cnae" name="cnae" class="form-control" type="text"
                                   placeholder="CNAE Principal"
                                   data-mask="99.99-9" readonly>
                        </div>
                        <div class="col-md-9">
                            <label for="cnae">Atividade Principal</label>
                            <input class="form-control" id="description" type="text"
                                   placeholder="Atividade Principal"
                                   readonly>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="sesmt">Atividades Secudárias</label>
                            <textarea id="sesmt" name="sesmt" rows="5" class="w-100" readonly></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label for="zipCode">CEP *</label>
                            <input class="form-control" name="zipCode" type="text" id="zipCode"
                                   placeholder="Cep" readonly>
                        </div>
                        <div class="col-md-2">
                            <label for="state">Estado *</label>
                            <input type="text" name="state" id="state" class="form-control" placeholder="UF"
                                   readonly>
                        </div>
                        <div class="col-md-3">
                            <label for="city">Cidade *</label>
                            <input type="text" name="city" id="city" class="form-control"
                                   placeholder="Cidade" readonly>
                        </div>
                        <div class="col-md-4">
                            <label for="neighborhood">Bairro *</label>
                            <input type="text" name="neighborhood" id="neighborhood" class="form-control"
                                   placeholder="Bairro" readonly>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="address">Logradouro *</label>
                            <input type="text" name="address" id="address" class="form-control"
                                   placeholder="Endereço" readonly>
                        </div>
                        <div class="col-md-2">
                            <label for="number">Número *</label>
                            <input type="text" name="number" id="number" class="form-control"
                                   placeholder="Número" readonly>
                        </div>
                        <div class="col-md-4">
                            <label for="complement">Complemento</label>
                            <input type="text" name="complement" id="complement" class="form-control"
                                   placeholder="Complemento" readonly>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label for="numbersOfWorkers">Qtd Trabalhadores *</label>
                            <input id="numbersOfWorkers" name="numbersOfWorkers" class="form-control"
                                   type="number"
                                   placeholder="Qtd Trabalhadores">
                        </div>
                        <div class="col-md-3">
                            <label for="phone">Telefone *</label>
                            <input id="phone" name="phone" class="form-control" type="text"
                                   placeholder="(99) 9999-9999" onkeyup="maskPhone(this, 'phone')">
                        </div>
                        <div class="col-md-6">
                            <label for="email">E-mail *</label>
                            <input id="email" name="email" class="form-control" type="email"
                                   placeholder="E-mail">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="logoCompany">Logo da Empresa</label><br>
                            <span class="fileselector">
                                  <label class="btn btn-block btn-danger text-whit" style="margin-top: 5px"
                                         for="logoCompany">
                                      <input class="upload-file-selector" id="logoCompany" type="file"
                                             name="logoCompany">
                                      <i class="fa fa-paperclip margin-correction"></i>
                                          <span id="logoCompanyLabel" default="Anexar Arquivo">Anexar Arquivo</span>
                                  </label>
                                </span>
                            <div class="galeria" id="logoCompanyImage"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <hr style="background-color: #002060">
                            <h6 class="title" style="color: black">Informações do Responsável</h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8">
                            <label for="representative">Representante Legal *</label>
                            <input name="representative" id="representative" class="form-control" type="text"
                                   placeholder="Representante Legal">
                        </div>
                        <div class="col-md-4">
                            <label for="representativePosition">Cargo Representante Legal *</label>
                            <select name="representativePosition" id="representativePosition"
                                    class="form-control form-select">
                                <option value="">Selecionar</option>
                                <option value="1">Proprietário</option>
                                <option value="2">Presidente</option>
                                <option value="3">Diretor Executivo</option>
                                <option value="4">Diretor Geral</option>
                                <option value="5">Chief Executive Officer - CEO</option>
                                <option value="6">Gerente Geral</option>
                                <option value="7">Preposto</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer px-3">
                    <div class="col d-flex flex-row-reverse">
                        <button type="submit" class="btn btn-primary">Salvar Empresa</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


</body>

<script>

    var baseurl = '<?= BASEURL ?>';

</script>
<!-- latest jquery-->
<script src="<?= BASEURL ?>assets/js/jquery-3.5.1.min.js?v=<?= time() ?>"></script>
<!-- feather icon js-->
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather-icon.js?v=<?= time() ?>"></script>
<!-- Sidebar jquery-->
<script src="<?= BASEURL ?>assets/js/sidebar-menu.js?v=<?= time() ?>"></script>
<!-- Bootstrap js-->
<script src="<?= BASEURL ?>assets/js/bootstrap/popper.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/bootstrap/bootstrap.min.js?v=<?= time() ?>"></script>
<!-- Plugins JS start-->
<script src="<?= BASEURL ?>assets/js/notify/bootstrap-notify.min.js?v=<?= time() ?>"></script>
<!-- Theme js-->
<script src="<?= BASEURL ?>assets/js/script.js?v=<?= time() ?>"></script>
<!-- Jquery mask-->
<script src="<?= BASEURL ?>assets/js/jquery.mask.js?v=<?= time() ?>"></script>

<script>

    function openModal() {
        $('#modal').modal('show');
        $('#message').hide();
        document.getElementById('addCompany').reset();
    }

    const formSelect = document.getElementById('selectCompany');

    formSelect.addEventListener('submit', e => {
        e.preventDefault();
        $('.form-control').removeClass('is-invalid is-valid');
        let formData = formDataToJson('selectCompany');
        if (formData.company.trim() == '') {
            $('#company').addClass('is-invalid');
            showNotify('danger', 'Selecione uma Empresa', 1500);
            return;
        } else {
            $('#company').addClass('is-valid');
        }
        fetch("<?= BASEURL ?>empresa/selecionar", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            response.json().then(json => {
                if (response.status === 200) {
                    showNotify('success', json.message, 2000);
                    setTimeout(function () {
                        window.location.href = `<?= BASEURL ?>empresa`;
                    }, 1500);
                } else {
                    showNotify('danger', json.message, 2000);
                }
            });
        });
    });

</script>

<script defer src="<?= BASEURL ?>assets/functions/functions.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/functions/company.js?v=<?= time() ?>"></script>

