<div class="page-body">
	<div class="container-fluid">
		<div class="col-xl-12">
			<div class="card">
				<div class="card-header pb-0">
					<form id="filter" autocomplete="off" class="form-group">
						<div class="row">
							<?php if ($user->getType() < 3): ?>
								<div class="col-md-3">
									<select id="clientFilter" name="client"
									        class="form-control form-select height-35 my-1">
										<option value="">Selecionar Cliente</option>
										<?php foreach ($clients as $client): ?>
											<option
												value="<?= $client->getClient()->getId() ?>"><?= $client->getName() ?></option>
										<?php endforeach; ?>
									</select>
								</div>
							<?php endif; ?>
							<div class="col-md-2 my-1">
								<select id="accountFilter" name="account" class="form-control form-select">
									<option value="">Selecionar Destino</option>
									<?php foreach ($accounts as $item): ?>
										<option value="<?= $item->getId() ?>"><?= $item->getName() ?></option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="col-md-2 my-1">
								<input id="startFilter" name="start" class="form-control" type="text"
								       placeholder="Dê dd/mm/AAAA" data-mask="99/99/9999">
							</div>
							<div class="col-md-2 my-1">
								<input id="endFilter" name="end" class="form-control" type="text"
								       placeholder="Até dd/mm/AAAA" data-mask="99/99/9999">
							</div>
							<div class="col-md-2 text-end d-sm-flex">
								<button class="btn btn-danger my-1" type="reset" onclick="resetTable()">Limpar
								</button>
								<button class="btn btn-primary my-1 m-l-10" type="submit">Buscar</button>
							</div>
						</div>
					</form>
					<hr>
				</div>
				<div class="card-body">
					<div class="row">
						<div class="col py-3">
							<span>Última atualização: </span><span id="created"></span>
						</div>
					</div>
					<div class="row table-responsive-md">
						<div class="col">
							<table class="table table-hover table-sm" id="tableTotal">
								<thead>
								<tr>
									<th class="text-center">
										Total de Depositos: <b><span class="text-success" id="totalLogIn"></span></b>
									</th>
									<th class="text-center">
										Total de Retiradas: <b><span class="text-danger" id="totalLogOut"></span></b>
									</th>
									<th class="text-center">
										SALDO: <b><span id="totalBalance"></span></b>
									</th>
								</tr>
								</thead>
							</table>
						</div>
					</div>
					<div class="row table-responsive-xxl">
						<div class="col">
							<table class="table table-hover table-sm" id="table">
								<thead>
								<tr>
									<?php if ($user->getType() < 3): ?>
										<th>Cliente</th>
									<?php endif; ?>
									<th class="text-center">Data Cadastro</th>
									<th class="text-center">DataOperação</th>
									<th class="text-center">Destino</th>
									<th class="text-center">Descrição</th>
									<th class="text-center">Cotação</th>
									<th class="text-center">Valor Reais</th>
									<th class="text-center">Valor Peso</th>
									<th class="text-center">Saldo</th>
								</tr>
								</thead>
								<tbody id="tableBody"></tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col text-center">
							<div class="spinner-border loaderTable" role="status">
								<span class="sr-only mx-auto">Loading...</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="<?= BASEURL ?>assets/functions/extract.js?v=<?= time() ?>"></script>
<script>
	var client = <?= $user->getType() == 3 ? $user->getClient()->getId() : 0 ?>;
</script>