<div class="page-body">
	<div class="container-fluid">
		<div class="col-xl-12">
			<div class="card">
				<div class="card-header pb-0">
					<form id="filter" autocomplete="off" class="form-group">
						<div class="row">
							<div class="col-md-5 d-sm-flex">
								<a class="btn btn-primary text-white m-r-30 height-35 my-1" href="#"
								   onclick="openModal(0)" style="min-width: 180px"><i
										class="fa fa-plus"></i> Saída</a>
								<select id="clientFilter" name="client" class="form-control form-select height-35 my-1">
									<option value="">Selecionar Cliente</option>
									<?php foreach ($clients as $client): ?>
										<option
											value="<?= $client->getClient()->getId() ?>"><?= $client->getName() ?></option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="col-md-2 my-1">
								<input id="startFilter" name="start" class="form-control" type="text"
								       placeholder="Dê dd/mm/AAAA" data-mask="99/99/9999">
							</div>
							<div class="col-md-2 my-1">
								<input id="endFilter" name="end" class="form-control" type="text"
								       placeholder="Até dd/mm/AAAA" data-mask="99/99/9999">
							</div>
							<div class="col-md-2 text-end d-sm-flex">
								<button class="btn btn-danger my-1" type="reset" onclick="resetTable()">Limpar
								</button>
								<button class="btn btn-primary my-1 m-l-10" type="submit">Buscar</button>
							</div>
						</div>
					</form>
					<hr>
				</div>
				<div class="card-body">
					<div class="row g-3 align-items-center m-b-30">
						<div class="col-auto">
							<span>Exibir </span>
						</div>
						<div class="col-auto">
							<select class="form-control form-select"
							        onchange="getLimit(this.value, 'equipamentTableBody')">
								<option value="25">25</option>
								<option value="50">50</option>
								<option value="100">100</option>
							</select>
						</div>
						<div class="col-auto">
							<span> registros</span>
						</div>
					</div>
					<div class="row">
						<div class="col">
							<p>Exibindo de <span id="start"></span> a <span id="end"></span> de <span
									id="total"></span> registros</p>
						</div>
					</div>
					<div class="row">
						<div class="col py-3">
							<span>Última atualização: </span><span id="created"></span>
						</div>
					</div>
					<div class="row table-responsive-xxl">
						<div class="col">
							<table class="table table-hover table-sm" id="table">
								<thead>
								<tr>
									<th>Cliente</th>
									<th class="text-center">Data</th>
									<th class="text-center">Valor Peso</th>
									<th class="text-center">Descrição</th>
									<?php if ($user->getType() == 1): ?>
										<th class="text-center">Ações</th>
									<?php endif; ?>
								</tr>
								</thead>
								<tbody id="tableBody"></tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col text-center">
							<div class="spinner-border loaderTable" role="status">
								<span class="sr-only mx-auto">Loading...</span>
							</div>
						</div>
					</div>
					<div class="row text-end">
						<nav aria-label="...">
							<ul class="pagination justify-content-end pagination-primary"
							    id="pagination" style="top: auto">

							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form id="addForm" method="post" autocomplete="off">
				<div class="modal-header">
					<h5 class="modal-title">Registro de Saída</h5>
					<button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="row mt-3">
					<div class="col text-center">
						<div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
							<span class="sr-only mx-auto">Loading...</span>
						</div>
					</div>
				</div>
				<div class="modal-body form-group">
					<input type="hidden" name="financialId" id="financialId">
					<input type="hidden" name="type" id="type" value="<?= $type ?>">
					<div class="row">
						<div class="col">
							<label for="client">Cliente *</label>
							<select id="client" name="client" class="form-control form-select">
								<option value="">Selecionar</option>
								<?php foreach ($clients as $client): ?>
									<option
										value="<?= $client->getClient()->getId() ?>"><?= $client->getName() ?></option>
								<?php endforeach; ?>
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<label for="valuePeso">Valor em Peso *</label>
							<input id="valuePeso" name="valuePeso" class="form-control" type="text"
							       placeholder="Valor em Peso">
						</div>
						<div class="col-md-6">
							<label for="date">Data *</label>
							<input id="date" name="date" class="form-control" type="text"
							       placeholder="dd/mm/AAAA" data-mask="99/99/9999">
						</div>
					</div>
					<div class="row">
						<div class="col">
							<label for="description">Descrição</label>
							<textarea id="description" name="description" class="form-control"
							          placeholder="Descrição da Saída" rows="3"></textarea>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="col text-end">
						<button type="submit" class="btn btn-primary">Salvar Saída</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="<?= BASEURL ?>assets/js/jquery.maskMoney.min.js"></script>
<script src="<?= BASEURL ?>assets/functions/financialLogOut.js?v=<?= time() ?>"></script>