<div class="page-body">
	<div class="container-fluid">
		<div class="col-xl-12">
			<div class="card">
				<div class="card-header pb-0">
					<form id="filter" autocomplete="off" class="form-group">
						<div class="row">
							<div class="col-md-8 d-sm-flex">
								<a class="btn btn-primary text-white m-r-30 height-35 my-1" href="#" onclick="openModal(0)" style="min-width: 180px"><i
										class="fa fa-plus"></i> Entrada</a>
								<input name="name" id="nameFilter" class="form-control my-1" placeholder="Nome">
							</div>
							<div class="col-md-4 text-end d-sm-flex">
								<button class="btn btn-danger my-1" type="reset" onclick="resetTable()">Limpar
								</button>
								<button class="btn btn-primary my-1 m-l-10" type="submit">Buscar</button>
							</div>
						</div>
					</form>
					<hr>
				</div>
				<div class="card-body">
					<div class="row g-3 align-items-center m-b-30">
						<div class="col-auto">
							<span>Exibir </span>
						</div>
						<div class="col-auto">
							<select class="form-control form-select"
							        onchange="getLimit(this.value, 'equipamentTableBody')">
								<option value="25">25</option>
								<option value="50">50</option>
								<option value="100">100</option>
							</select>
						</div>
						<div class="col-auto">
							<span> registros</span>
						</div>
					</div>
					<div class="row">
						<div class="col">
							<p>Exibindo de <span id="start"></span> a <span id="end"></span> de <span
									id="total"></span> registros</p>
						</div>
					</div>
					<div class="row table-responsive-xxl">
						<div class="col">
							<table class="table table-hover table-sm" id="table">
								<thead>
								<tr>
									<th>Cliente</th>
									<th class="text-center">Remetente</th>
									<th class="text-center">Destino</th>
									<th class="text-center">Valor Real</th>
									<th class="text-center">Valor Peso</th>
									<th class="text-center">Ações</th>
								</tr>
								</thead>
								<tbody id="tableBody"></tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col text-center">
							<div class="spinner-border loaderTable" role="status">
								<span class="sr-only mx-auto">Loading...</span>
							</div>
						</div>
					</div>
					<div class="row text-end">
						<nav aria-label="...">
							<ul class="pagination justify-content-end pagination-primary"
							    id="pagination" style="top: auto">
							
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form id="addForm" method="post" autocomplete="off">
				<div class="modal-header">
					<h5 class="modal-title">Registro de Entrada</h5>
					<button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="row mt-3">
					<div class="col text-center">
						<div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
							<span class="sr-only mx-auto">Loading...</span>
						</div>
					</div>
				</div>
				<div class="modal-body form-group">
					<input type="hidden" name="financialId" id="financialId">
					<input type="hidden" name="type" id="type" value="<?= $type ?>">
					<div class="row">
						<div class="col">
							<label for="client">Cliente *</label>
							<select id="client" name="client" class="form-control form-select">
								<option value="">Selecionar</option>
								<?php foreach ($clients as $client): ?>
								<option value="<?= $client->getClient()->getId() ?>"><?= $client->getName() ?></option>
								<?php endforeach; ?>
							</select>
						</div>
					</div>
					<div class="row">
						<div class="col">
							<label for="sender">Remetente *</label>
							<input id="sender" name="sender" class="form-control" type="text"
							       placeholder="Remetente">
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<label for="destiny">Conta Destino *</label>
							<select id="destiny" name="destiny" class="form-control form-select">
								<option value="">Selecionar</option>
									<option value="1">Conta 1</option>
									<option value="2">Conta 2</option>
							</select>
						</div>
						<div class="col-md-6">
							<label for="valueReal">Valor em Real *</label>
							<input id="valueReal" name="valueReal" class="form-control" type="text"
							       placeholder="Valor em Real">
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<label for="price">Cotação *</label>
							<input id="price" name="price" class="form-control" type="text"
							       placeholder="Cotação" onblur="setValuePeso()">
						</div>
						<div class="col-md-6">
							<label for="valuePeso">Valor em Peso *</label>
							<input id="valuePeso" name="valuePeso" class="form-control" type="text"
							       placeholder="Valor em Peso" readonly>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<label for="code">Código *</label>
							<input id="code" name="code" class="form-control" type="text"
							       placeholder="Código">
						</div>
						<div class="col-md-6">
							<label for="date">Data *</label>
							<input id="date" name="date" class="form-control" type="text"
							       placeholder="dd/mm/AAAA" data-mask="99/99/9999">
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="col text-end">
						<button type="submit" class="btn btn-primary">Salvar Entrada</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="<?= BASEURL ?>assets/js/jquery.maskMoney.min.js"></script>
<script src="<?= BASEURL ?>assets/functions/financialLogIn.js?v=<?= time() ?>"></script>