
<footer class="footer">
  <div class="container-fluid text-center">
    ©
    <script>
        document.write(new Date().getFullYear());</script>,
        Criado por <a href="https://plennum.com.br/" target="_blank" class="text-primary">Plennum</a> e Desenvolvido por <a href="https://www.lifecode.dev/" class="text-yellow"
                                                        target="_blank">Life Code</a>
  </div>
</footer>
</body>
<script src="<?= BASEURL ?>assets/functions/functions.js?v=<?= time() ?>"></script>
<!-- Bootstrap js-->
<script src="<?= BASEURL ?>assets/js/bootstrap/popper.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/bootstrap/bootstrap.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/notify/bootstrap-notify.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/jquery.mask.js"></script>
</html>
