<!DOCTYPE html>
<html lang="pt-br" style="overflow-y: scroll">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description"
	      content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
	<meta name="keywords"
	      content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
	<meta name="author" content="pixelstrap">
	<link rel="icon" href="<?= BASEURL ?>assets/img/icon.jpeg" type="image/x-icon">
	<link rel="shortcut icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
	<title>FlashMoney - <?= $title ?></title>
	<!-- Google font-->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link
		href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
		rel="stylesheet">
	<link
		href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap"
		rel="stylesheet">
	<link
		href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
		rel="stylesheet">
	<!-- ico-font-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/icofont.css?v=<?= time() ?>">
	<!-- Feather icon-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/feather-icon.css?v=<?= time() ?>">
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/themify.css?v=<?= time() ?>">
	<!-- Plugins css start-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/animate.css?v=<?= time() ?>">
	<!-- Plugins css Ends-->
	<!-- Bootstrap css-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.css?v=<?= time() ?>">
	<!-- App css-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>">
	<link id="color" rel="stylesheet" href="<?= BASEURL ?>assets/css/color-1.css?v=<?= time() ?>" media="screen">
	<!-- Responsive css-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/responsive.css?v=<?= time() ?>">

	<script src="https://kit.fontawesome.com/b1f34ab4bc.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/newStyle.css?v=<?= time() ?>">
</head>
<body>
<!-- Loader starts-->
<div class="loader-wrapper">
	<div class="theme-loader">
		<div class="loader-p"></div>
	</div>
</div>
<!-- Loader ends-->
<!-- page-wrapper Start       -->
<div class="page-wrapper compact-wrapper compact-sidebar" id="pageWrapper">
	<!-- Page Header Start-->
	<div class="page-main-header">
		<div class="main-header-right row m-0">
			<div class="main-header-left">
				<div class="logo-wrapper">
					<a href="<?= BASEURL ?>empresa">
						<img height="40px" src="<?= BASEURL ?>assets/img/logo.jpeg" alt="LogoFlashMoney">
					</a>
				</div>
				<div class="toggle-sidebar"><i class="status_toggle middle" data-feather="align-center"
				                               id="sidebar-toggle"></i></div>
			</div>
			<div class="left-menu-header col">
				<ul>
					<li style="display: flex">
						<div class="text-center" style="white-space: normal">
							<i class="fas fa-user m-r-10"></i>
							<span style="color:rgb(22, 142, 234);"><?= $user->getName() ?></span>
						</div>
					</li>
				</ul>
			</div>
			<div class="nav-right col pull-right right-menu p-0">
				<ul class="nav-menus">
					<li class="onhover-dropdown">
						<div class="bookmark-box">
							<?php if ($user->getImg()): ?>
								<img style="border-radius: 50%; max-height: 40px"
								     src="<?= BASEURL ?>uploads/<?= $user->getImg() ?>" alt="ImagemPerfil">
							<?php else: ?>
								<img style="border-radius: 50%; max-height: 40px"
								     src="<?= BASEURL ?>assets/img/user.png" alt="ImagemGenerica">
							<?php endif; ?>
						</div>
						<div class="bookmark-dropdown onhover-show-div">
							<ul class="m-t-5 w-100">
								<li class="add-to-bookmark w-100" onclick="redirect(1)">
									<a href="<?= BASEURL ?>usuarios/meu-perfil" class="w-100">
										<i class="bookmark-icon" data-feather="user">
										</i>Meu Perfil
									</a>
								</li>
								<li class="add-to-bookmark" onclick="redirect(2)">
									<a href="<?= BASEURL ?>logout"><i class="bookmark-icon" data-feather="log-out"></i>Sair</a>
								</li>
							</ul>
						</div>
					</li>
				</ul>
			</div>
			<div class="d-lg-none mobile-toggle pull-right w-auto"><i data-feather="more-horizontal"></i></div>
		</div>
	</div>
	<!-- Page Header Ends                              -->
	<!-- Page Body Start-->
	<div class="page-body-wrapper sidebar-icon">
		<!-- Page Sidebar Start-->
		<header class="main-nav">
			<nav>
				<div class="main-navbar mt-3">
					<div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
					<div id="mainnav">
						<ul class="nav-menu custom-scrollbar">

							<li style="margin-top: -45px">
								<a class="nav-link link-nav <?= in_array('home', $menuActive) ? 'active-dash' : '' ?>"
								   href="<?= BASEURL ?>">
									<i data-feather="home"></i><span> Home</span>
								</a>
							</li>

							<?php if ($user->getType() == 1): ?>
								<li>
									<a class="nav-link link-nav <?= in_array('users', $menuActive) ? 'active-dash' : '' ?>"
									   href="<?= BASEURL ?>usuarios">
										<i data-feather="users"></i><span>Usuários</span>
									</a>
								</li>

								<li>
									<a class="nav-link link-nav <?= in_array('accounts', $menuActive) ? 'active-dash' : '' ?>"
									   href="<?= BASEURL ?>contas">
										<span class="f-22">
											<i class="fa fa-bank pt-3 pb-3"></i>
										</span>
										<span>Contas</span>
									</a>
								</li>
							<?php endif; ?>
							<?php if ($user->getType() < 3): ?>
								<li>
									<a class="nav-link link-nav <?= in_array('clients', $menuActive) ? 'active-dash' : '' ?>"
									   href="<?= BASEURL ?>clientes">
										<i data-feather="dollar-sign"></i><span>Clientes</span>
									</a>
								</li>

								<li>
									<a class="nav-link link-nav <?= in_array('log-in', $menuActive) ? 'active-dash' : '' ?>"
									   href="<?= BASEURL ?>entradas">
										<i data-feather="log-in"></i><span>Entradas</span>
									</a>
								</li>

								<li>
									<a class="nav-link link-nav <?= in_array('log-out', $menuActive) ? 'active-dash' : '' ?>"
									   href="<?= BASEURL ?>saidas">
										<i data-feather="log-out"></i><span>Saídas</span>
									</a>
								</li>
							<?php endif; ?>

							<li>
								<a class="nav-link link-nav <?= in_array('extract', $menuActive) ? 'active-dash' : '' ?>"
								   href="<?= BASEURL ?>extratos">
									<i data-feather="list"></i><span>Extratos</span>
								</a>
							</li>

						</ul>
					</div>
					<div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
				</div>
			</nav>
		</header>
		<!-- Page Sidebar Ends-->
		<!-- latest jquery-->
		<script src="<?= BASEURL ?>assets/js/jquery-3.5.1.min.js?v=<?= time() ?>"></script>
		<!-- feather icon js-->
		<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather.min.js?v=<?= time() ?>"></script>
		<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather-icon.js?v=<?= time() ?>"></script>
		<!-- Sidebar jquery-->
		<script src="<?= BASEURL ?>assets/js/sidebar-menu.js?v=<?= time() ?>"></script>
		<!-- Theme js-->
		<script src="<?= BASEURL ?>assets/js/script.js?v=<?= time() ?>"></script>
		<script src="<?= BASEURL ?>assets/js/jquery.mask.js?v=<?= time() ?>"></script>
		<!-- Plugins JS start-->
		<script src="<?= BASEURL ?>assets/js/scrollable/perfect-scrollbar.min.js?v=<?= time() ?>"></script>
		<script src="<?= BASEURL ?>assets/js/scrollable/scrollable-custom.js?v=<?= time() ?>"></script>


		<script>

			var baseurl = '<?= BASEURL ?>';
			var type = <?= $user->getType() ?>;
			var client = <?= $user->getType() ?>;

			function redirect(type) {
				if (type == 1) {
					window.location.href = `${baseurl}usuarios/meu-perfil`
				} else if (type == 2) {
					window.location.href = `${baseurl}logout`
				}
			}


		</script>