<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
          content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="<?= BASEURL ?>assets/img/icon.jpeg" type="image/x-icon">
    <link rel="shortcut icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <title>FlashMoney - Login</title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
	<!-- ico-font-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/icofont.css?v=<?= time() ?>">
	<!-- Themify icon-->
	<link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/themify.css?v=<?= time() ?>">
    <!-- Font Awesome-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/fontawesome.css?v=<?= time() ?>">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/feather-icon.css?v=<?= time() ?>">
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.css?v=<?= time() ?>">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>">
    <link id="color" rel="stylesheet" href="<?= BASEURL ?>assets/css/color-1.css?v=<?= time() ?>" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/responsive.css?v=<?= time() ?>">
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/newStyle.css?v=<?= time() ?>">
</head>
<body>
<!-- Loader starts-->
<div class="loader-wrapper">
    <div class="theme-loader">
        <div class="loader-p"></div>
    </div>
</div>
<!-- Loader ends-->
<!-- page-wrapper Start-->
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-7 order-1"><img class="bg-img-cover bg-center"
                                               src="<?= BASEURL ?>assets/img/login.jpeg" alt="looginpage"></div>
            <div class="col-xl-5 p-0">
                <div class="login-card">
                    <form class="theme-form login-form needs-validation form-group" autocomplete="off" method="post">
                        <h4>Login</h4>
                        <h6>Bem vindo de volta! Faça login na sua conta.</h6>
                        <label for="email">Email</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="icon-email"></i></span>
                            <input class="form-control" id="email" name="email" type="email" required=""
                                   placeholder="email@gmail.com">
                        </div>
                        <label for="password">Senha</label>
                        <div class="input-group">
                            <span class="input-group-text"><i class="icon-lock"></i></span>
                            <input class="form-control" id="password" type="password" name="password" required=""
                                   placeholder="*********">
                        </div>
                        <div class="d-flex justify-content-between">
                            <a class="link" href="<?= BASEURL ?>cadastrar">Fazer cadastro</a>
                            <a class="link" href="<?= BASEURL ?>recuperar">Esqueceu a senha?</a>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary btn-block m-t-10" type="submit">Login</button>
                        </div>
                        <div class="row">
                            <div class="col">
								<?php if (\App\Helpers\Session::get('errorMsg')): ?>
                                    <div class="alert alert-danger text-center mx-2"><?= \App\Helpers\Session::get('errorMsg') ?></div>
									<?php \App\Helpers\Session::forgot('errorMsg'); ?>
								<?php endif; ?>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- page-wrapper end-->
<script>
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>
<!-- latest jquery-->
<script src="<?= BASEURL ?>assets/js/jquery-3.5.1.min.js?v=<?= time() ?>"></script>
<!-- feather icon js-->
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather-icon.js?v=<?= time() ?>"></script>
<!-- Bootstrap js-->
<script src="<?= BASEURL ?>assets/js/bootstrap/popper.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/bootstrap/bootstrap.min.js?v=<?= time() ?>"></script>
<!-- Theme js-->
<script src="<?= BASEURL ?>assets/js/script.js?v=<?= time() ?>"></script>
</body>
</html>