<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
          content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <title>GEind - Recuperar Senha</title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/icofont.css?v=<?= time() ?>">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/themify.css?v=<?= time() ?>">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/feather-icon.css?v=<?= time() ?>">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/animate.css?v=<?= time() ?>">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.css?v=<?= time() ?>">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>">
    <link id="color" rel="stylesheet" href="<?= BASEURL ?>assets/css/color-1.css?v=<?= time() ?>" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/responsive.css?v=<?= time() ?>">

    <script src="https://kit.fontawesome.com/b1f34ab4bc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/newStyle.css?v=<?= time() ?>">
</head>

<body>
<!-- Loader starts-->
<div class="loader-wrapper">
    <div class="theme-loader">
        <div class="loader-p"></div>
    </div>
</div>
<!-- Loader ends-->
<!-- page-wrapper Start-->
<section>
    <div class="container-fluid p-0">
        <div class="row m-0">
            <div class="col-12 p-0">
                <div class="login-card" style="height: 100%;">
                    <div class="login-main">
                        <form class="theme-form login-form" id="recover">
                            <h4 class="mb-3">Redefinir sua Senha</h4>
                            <div class="form-group">
                                <label for="email">Digite seu e-mail de acesso</label>
                                <input class="form-control" type="email" required name="email" id="email">
                            </div>
                            <div class="form-group row">
                                <div class="col-md-8 text-center">
                                    <div class="spinner-border loaderTable-1" role="status" style="opacity: 0;">
                                        <span class="sr-only mx-auto">Loading...</span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <a class="btn btn-primary" onclick="submitForm('post', 'recover')">Enviar</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <span class="reset-password-link">Não recebeu o código de verficação?
                                    <a class="btn-link text-danger" onclick="submitForm('post', 'recover')">Reenviar</a>
                                </span>
                            </div>
                        </form>
                        <form class="theme-form login-form" style="margin-top: -70px" id="change">
                            <div class="form-group">
                                <input type="hidden" id="token" name="token">
                                <input type="hidden" id="emailHidden" name="email">
                                <label>Digite o Código</label>
                                <div class="row">
                                    <div class="col">
                                        <input class="form-control text-center opt-text code" type="text"
                                               placeholder="00" id="1"
                                               maxlength="2" name="code-1">
                                    </div>
                                    <div class="col">
                                        <input class="form-control text-center opt-text code" type="text"
                                               placeholder="00" maxlength="2" name="code-2" id="2">
                                    </div>
                                    <div class="col">
                                        <input class="form-control text-center opt-text code" type="text"
                                               maxlength="2" name="code-3" id="3">
                                    </div>
                                </div>
                            </div>
                            <h6>Crie sua senha</h6>
                            <div class="form-group">
                                <label>Nova Senha</label>
                                <div class="input-group"><span class="input-group-text"><i class="icon-lock"></i></span>
                                    <input class="form-control" type="password" name="password" required=""
                                           placeholder="*********">
                                    <div class="show-hide"><span class="show"></span></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Confirmar Senha</label>
                                <div class="input-group"><span class="input-group-text"><i class="icon-lock"></i></span>
                                    <input class="form-control" type="password" name="password2" required=""
                                           placeholder="*********">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-md-8 text-center">
                                    <div class="spinner-border loaderTable-2" role="status" style="opacity: 0">
                                        <span class="sr-only mx-auto">Loading...</span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <a class="btn btn-primary" onclick="submitForm('put', 'change')">Enviar</a>
                                </div>
                            </div>
                            <p>Já tem uma senha?<a class="ms-2" href="<?= BASEURL ?>login">Login</a></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

<script>

    var baseurl = '<?= BASEURL ?>';

</script>

<!-- latest jquery-->
<script src="<?= BASEURL ?>assets/js/jquery-3.5.1.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/jquery.mask.js?v=<?= time() ?>"></script>
<!-- feather icon js-->
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather-icon.js?v=<?= time() ?>"></script>
<!-- Bootstrap js-->
<script src="<?= BASEURL ?>assets/js/bootstrap/popper.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/bootstrap/bootstrap.min.js?v=<?= time() ?>"></script>
<!-- Theme js-->
<script src="<?= BASEURL ?>assets/js/script.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/notify/bootstrap-notify.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/functions/functions.js?v=<?= time() ?>"></script>
<script>

    const form = document.getElementById('recover');

    $(document).ready(function () {
        $('.code').mask("00", {placeholder: "00"});
        $('.code').val("");
        $(".code").keyup(function() {
            if (this.value.length == this.maxLength) {
                let number = parseInt($(this).attr('id')) + 1;
                $('#' + number).focus();
            }
        });
        setTimeout(function () {
            document.getElementById('change').reset()
        }, 500);
    });

    function submitForm(method, submit){
        $('.btn').attr('disabled', true);
        if (submit == 'recover') $('.loaderTable-1').css('opacity', 1);
        if (submit == 'change') $('.loaderTable-2').css('opacity', 1);
        let url = "<?= BASEURL ?>recuperar/";
        let formData = formDataToJson(submit);
        fetch(url, {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            $('.btn').attr('disabled', false);
            if (submit == 'recover') $('.loaderTable-1').css('opacity', 0);
            if (submit == 'change') $('.loaderTable-2').css('opacity', 0);
            response.json().then(json => {
                if (response.status === 200) {
                    showNotify('success', json.message, 1500);
                    document.getElementById(submit).reset();
                    $('#token').val(json.token);
                    if (submit == 'change') {
                        setTimeout(function () {
                            window.location.href = '<?= BASEURL ?>login';
                        }, 2000)
                    }
                } else {
                    showNotify('danger', json.message, 1500);
                }
            });
        });
    }
</script>


