<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="viho admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
          content="admin template, viho admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <link rel="shortcut icon" href="<?= BASEURL ?>assets/images/favicon.png" type="image/x-icon">
    <title>GEind - <?= $title ?></title>
    <!-- Google font-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
          rel="stylesheet">
    <!-- ico-font-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/icofont.css?v=<?= time() ?>">
    <!-- Themify icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/themify.css?v=<?= time() ?>">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/flag-icon.css?v=<?= time() ?>">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/feather-icon.css?v=<?= time() ?>">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/animate.css?v=<?= time() ?>">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/bootstrap.css?v=<?= time() ?>">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/style.css?v=<?= time() ?>">
    <link id="color" rel="stylesheet" href="<?= BASEURL ?>assets/css/color-1.css?v=<?= time() ?>" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/responsive.css?v=<?= time() ?>">

    <script src="https://kit.fontawesome.com/b1f34ab4bc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="<?= BASEURL ?>assets/css/newStyle.css?v=<?= time() ?>">
</head>

<body style="overflow-x: hidden; background: rgb(231, 239, 238)">
<div class="row" style="background: rgb(52, 58, 64)">
    <div class="col text-center p-2">
        <img src="<?= BASEURL ?>assets/img/logo2.png" alt="logoSisgg" style="height: 100px">
    </div>
</div>
<div class="container py-5">
    <div class="col mb-3 p-3" style="background: white">
        <div class="row mt-3">
            <div class="col text-center">
                <div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
                    <span class="sr-only mx-auto">Loading...</span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <h4 class="mb-3">Realizar Cadastro</h4>
                <hr style="border-color: rgb(52, 58, 64)">
                <h6>Dados da Consultoria</h6>
            </div>
        </div>
        <form id="formConsultant" autocomplete="off">
            <div class="form-group">
                <div class="row">
                    <div class="col-md-4">
                        <label for="consultant">Consultoria</label><span> *</span>
                        <input id="consultant" name="consultant" placeholder="Consultoria" type="text"
                               class="form-control">
                    </div>
                    <div class="col-md-2">
                        <label for="cpf">CPF</label><span> *</span>
                        <input id="cpf" name="cpf" placeholder="___.___.___-__" type="text" class="form-control"
                               data-mask="999.999.999-99">
                    </div>
                    <div class="col-md-3">
                        <label for="cnpj">CNPJ</label><span> *</span>
                        <input id="cnpj" name="cnpj" placeholder="__.___.___/____-__" type="text" class="form-control"
                               data-mask="99.999.999/9999-99">
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label for="zipCode">CEP</label><span> *</span>
                            <input class="form-control" name="zipCode" data-mask="99999-999" type="text" id="zipCode"
                                   placeholder="CEP">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="uf">Estado</label><span> *</span>
                            <input type="text" name="uf" id="uf" class="form-control" placeholder="UF">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="city">Cidade</label><span> *</span>
                            <input type="text" name="city" id="city" class="form-control" placeholder="Cidade">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="neighborhood">Bairro</label><span> *</span>
                            <input type="text" name="neighborhood" id="neighborhood" class="form-control"
                                   placeholder="Bairro">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="address">Endereço</label><span> *</span>
                            <input type="text" name="address" id="address" class="form-control" placeholder="Endereço">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="complement">Complemento</label><span> *</span>
                        <input type="text" name="complement" id="complement" class="form-control"
                               placeholder="Complemento">
                    </div>
                    <div class="col-md-2">
                        <label for="number">Número</label>
                        <input type="text" name="number" id="number" class="form-control" placeholder="Número">
                    </div>
                    <div class="col-md-2">
                        <label for="phone">Telefone</label><span> *</span>
                        <input type="text" name="phone" id="phone" class="form-control" placeholder="(__) ____-____"
                               onkeyup="maskPhone(this, 'phone')">
                    </div>
                    <div class="col-md-4">
                        <label for="emailConsultant">E-mail Consultoria</label><span> *</span>
                        <input type="email" name="emailConsultant" id="emailConsultant" class="form-control"
                               placeholder="E-mail Consultoria">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <label for="contract">Logo da Consultoria</label>
                        <span class="fileselector">
                                  <label class="btn btn-block btn-danger text-white" style="margin-top: -1px"
                                         for="logoCompany">
                                      <input class="upload-file-selector" id="logoCompany" type="file"
                                             name="logoCompany">
                                      <i class="fa fa-paperclip margin-correction"></i>
                                          <span id="logoCompanyLabel" default="Anexar Arquivo">Anexar Arquivo</span>
                                  </label>
                                </span>
                        <div class="galeria" id="logoCompanyImage"></div>
                    </div>
                </div>
                <div class="col p-2">
                    <hr style="border-color: rgb(52, 58, 64)">
                    <h6>Plano e Forma de Pagamento</h6>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label for="name1">Nome</label>
                        <input id="name1" name="name1" placeholder="Nome" type="text" class="form-control">
                    </div>
                    <div class="col-md-3">
                        <label for="email1">E-mail</label>
                        <input id="email1" name="email1" placeholder="E-mail" type="email" class="form-control">
                    </div>
                    <div class="col-md-3">
                        <label for="password1">Senha</label>
                        <input id="password1" name="password1" placeholder="Senha" type="password" class="form-control">
                        <span style="font-size: 8px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                    </div>
                    <div class="col-md-3">
                        <label for="password21">Confirme a Senha</label>
                        <input id="password21" name="password21" placeholder="Confirme a Senha" type="password"
                               class="form-control">
                        <span style="font-size: 8px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                    </div>
                </div>
                <div class="col p-2">
                    <hr style="border-color: rgb(52, 58, 64)">
                    <h6>Dados de Acesso de Primeiro Usuário</h6>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label for="name">Nome</label><span> *</span>
                        <input id="name" name="name" placeholder="Nome" type="text" class="form-control">
                    </div>
                    <div class="col-md-3">
                        <label for="email">E-mail</label><span> *</span>
                        <input id="email" name="email" placeholder="E-mail" type="email" class="form-control">
                    </div>
                    <div class="col-md-3">
                        <label for="password">Senha</label><span> *</span>
                        <input id="password" name="password" placeholder="Senha" type="password" class="form-control">
                        <span style="font-size: 8px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                    </div>
                    <div class="col-md-3">
                        <label for="password2">Confirme a Senha</label><span> *</span>
                        <input id="password2" name="password2" placeholder="Confirme a Senha" type="password"
                               class="form-control">
                        <span style="font-size: 8px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                    </div>
                </div>
            </div>
            <div class="row my-2">
                <div class="col text-end">
                    <button type="submit" class="btn btn-primary">Cadastrar</button>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
<footer style="background: rgb(52, 58, 64); margin-left: 0">
    <div class="row">
        <div class="col text-center p-2">
            <img src="<?= BASEURL ?>assets/img/logo2.png" alt="logoSisgg" style="height: 80px">
        </div>
</footer>

<!-- latest jquery-->
<script src="<?= BASEURL ?>assets/js/jquery-3.5.1.min.js?v=<?= time() ?>"></script>
<!-- feather icon js-->
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/icons/feather-icon/feather-icon.js?v=<?= time() ?>"></script>
<!-- Sidebar jquery-->
<script src="<?= BASEURL ?>assets/js/sidebar-menu.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/config.js?v=<?= time() ?>"></script>
<!-- Bootstrap js-->
<script src="<?= BASEURL ?>assets/js/bootstrap/popper.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/bootstrap/bootstrap.min.js?v=<?= time() ?>"></script>
<!-- Plugins JS start-->
<script src="<?= BASEURL ?>assets/js/clipboard/clipboard.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/counter/jquery.counterup.min.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/counter/counter-custom.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/custom-card/custom-card.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/notify/bootstrap-notify.min.js?v=<?= time() ?>"></script>
<!-- Theme js-->
<script src="<?= BASEURL ?>assets/js/script.js?v=<?= time() ?>"></script>
<!-- login js-->
<script defer src="<?= BASEURL ?>assets/functions/functions.js?v=<?= time() ?>"></script>
<script src="<?= BASEURL ?>assets/js/jquery.mask.js?v=<?= time() ?>"></script>

<script>

    const form = document.getElementById('formConsultant');

    function validateForm() {
        $('.form-control').removeClass('is-invalid');
        let errors = [];
        let ids = [];
        const formData = formDataToJson('formConsultant');

        if (formData.consultant.trim() == '') {
            errors.push('<b> Consultoria</b>');
            ids.push('consultant');
        }
        if (formData.cpf.trim() == '' && formData.cnpj.trim() == '') {
            errors.push('<b> CPF ou CNPJ</b>');
            ids.push('cpf');
            ids.push('cnpj')
        }
        if (formData.zipCode.trim() == '') {
            errors.push('<b> CEP</b>');
            ids.push('zipCode');
        }
        if (formData.uf.trim() == '') {
            errors.push('<b> Estado</b>');
            ids.push('uf');
        }
        if (formData.city.trim() == '') {
            errors.push('<b> Cidade</b>');
            ids.push('city');
        }
        if (formData.neighborhood.trim() == '') {
            errors.push('<b> Bairro</b>');
            ids.push('neighborhood');
        }
        if (formData.address.trim() == '') {
            errors.push('<b> Endereço</b>');
            ids.push('address');
        }
        if (formData.complement.trim() == '') {
            errors.push('<b> Complemento</b>');
            ids.push('complement');
        }
        if (formData.phone.trim() == '') {
            errors.push('<b> Telefone</b>');
            ids.push('phone');
        }
        if (formData.emailConsultant.trim() == '') {
            errors.push('<b> E-mail Consultoria</b>');
            ids.push('emailConsultant');
        }
        if (formData.name.trim() == '') {
            errors.push('<b> Nome</b>');
            ids.push('name');
        }
        if (formData.email.trim() == '') {
            errors.push('<b> Email</b>');
            ids.push('email');
        }
        if (formData.password.trim() == '') {
            errors.push('<b> Senha</b>');
            ids.push('password');
        }
        if (formData.password2.trim() == '') {
            errors.push('<b> Confirme a Senha</b>');
            ids.push('password2');
        }

        if (errors.length > 0) {
            let message = '';
            if (errors.length == 1) message = 'O campo';
            if (errors.length > 1) message = 'Os campos';

            for (i = 0; i < errors.length; i++) {
                message += errors[i];
                if (i == errors.length - 2) message += ' e';
                if (i < errors.length - 2) message += ',';
            }

            if (errors.length == 1) message += ' é obrigatório!';
            if (errors.length > 1) message += ' são obrigatórios!';

            for (i = 0; i < ids.length; i++) {
                $('#' + ids[i]).addClass('is-invalid');
            }
            showNotify('danger', message, 4000);
            return false;
        }
        if (formData.password != '' && formData.password != formData.password2) {
            showNotify('danger', 'As senhas estão diferentes!', 2000);
            return false;
        }
        return true;
    }

    form.addEventListener('submit', e => {
        e.preventDefault();
        startLoading();
        if (!validateForm()) {
            $('.loaderTop').hide();
            $('.form-group').css('opacity', 1);
            $('.btn').attr('disabled', false);
            window.stop();
        } else {
            let formData = formDataToJson('formConsultant');
            fetch('<?= BASEURL ?>cadastrar', {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                },
                body: new FormData(form)
            }).then(response => {
                $('.loaderTop').hide();
                $('.form-group').css('opacity', 1);
                $('.btn').attr('disabled', false);
                response.json().then(json => {
                    if (response.status === 200) {
                        showNotify('success', json.message, 2000);
                        form.reset();
                        setTimeout(function () {
                            window.location.href = `<?= BASEURL ?>login`;
                        }, 2000);
                    } else {
                        showNotify('danger', json.message, 2000);
                    }
                });
            });
        }
    });

    $(document).ready(function () {
        $("#zipCode").keyup(function () {
            loadAddress();
        });
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let string = input.value.replace('fakepath', '');

                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = string.slice(4);
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });

    function loadAddress() {
        var cep = $('#zipCode').val().replace(/\D/g, '');
        var validacep = /^[0-9]{8}$/;
        if (validacep.test(cep)) {
            $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
                if (!("erro" in dados)) {
                    $("#uf").val(dados.uf);
                    $("#city").val(dados.localidade);
                    $("#neighborhood").val(dados.bairro);
                    $("#address").val(dados.logradouro);
                    $("#complement").val(dados.complemento);
                }
            });
        }
    }

    function maskPhone(phone, id) {

        let teste = document.getElementById(id).value;
        let caracter = teste.replace(/\D/gim, '');
        let tamanho = caracter.length;

        if (tamanho <= 10) {
            caracter = caracter.replace(/(\d{2})(\d)/, "($1) $2");
            caracter = caracter.replace(/(\d{4})(\d)/, "$1-$2");
            return document.getElementById(id).value = caracter;
        } else if (tamanho >= 11) {
            caracter = caracter.replace(/(\d{2})(\d)/, "($1) $2");
            caracter = caracter.replace(/(\d{5})(\d)/, "$1-$2");
            return document.getElementById(id).value = caracter.substring(0, 15)
        }
    }
</script>

</html>
