<div class="page-body">
	<!-- Container-fluid starts-->
	<div class="container-fluid m-t-20">
		<div class="row">
			<div class="col-xl-12">
				<div class="card">
					<div class="card-header">
						<form id="filter" autocomplete="off" class="m-t-10">
							<div class="row">
								<div class="col-md-5 d-sm-flex">
									<a class="float-right btn btn-primary text-white w-150 m-r-30 height-35 my-1" href="#"
									   onclick="openModal(0)">Usuário <i class="fa fa-plus"></i></a>
									<input class="form-control height-35 my-1" id="nameFilter" name="name" type="text"
									       placeholder="Nome">
								</div>
								<div class="col-md-2 my-1">
									<input class="form-control" id="emailFilter" name="email" type="text"
									       placeholder="E-mail">
								</div>
								<div class="col-md-2 my-1">
									<select name="type" id="typeFilter" class="form-control form-select">
										<option value="0">Selecionar</option>
										<option value="1">Admin</option>
										<option value="2">Convencional</option>
									</select>
								</div>
								<div class="col text-end d-sm-flex">
									<button class="btn btn-danger my-1" type="reset" onclick="resetTable()">Limpar</button>
									<button class="btn btn-primary my-1 m-l-10" type="submit">Filtrar</button>
								</div>
							</div>
						</form>
					</div>
					<div class="card-body">

						<div class="row g-3 align-items-center m-b-30">
							<div class="col-auto">
								<span>Exibir </span>
							</div>
							<div class="col-auto">
								<select class="form-control form-select"
								        onchange="getLimit(this.value, 'tableBody')">
									<option value="25">25</option>
									<option value="50">50</option>
									<option value="100">100</option>
								</select>
							</div>
							<div class="col-auto">
								<span> registros</span>
							</div>
						</div>
						<div class="row">
							<div class="col">
								<p>Exibindo de <span id="start"></span> a <span id="end"></span> de <span
										id="total"></span> registros</p>
							</div>
						</div>
						<div class="row table-responsive-lg">
							<div class="col">
								<table class="table table-hover " id="table">
									<thead>
									<tr>
										<th>Nome</th>
										<th class="text-center">Nível</th>
										<th class="text-center">E-mail</th>
										<th class="text-center">Status</th>
										<th class="text-center">Ações</th>
									</tr>
									</thead>
									<tbody id="tableBody"></tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col text-center">
								<div class="spinner-border loaderTable" role="status">
									<span class="sr-only mx-auto">Loading...</span>
								</div>
							</div>
						</div>
						<div class="row text-end">
							<nav aria-label="...">
								<ul class="pagination justify-content-end pagination-primary"
								    id="pagination" style="top: auto">

								</ul>
							</nav>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<form id="addForm" method="post" autocomplete="off">
				<div class="modal-header">
					<h5 class="modal-title">Registro de Usuário</h5>
					<button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="row mt-3">
					<div class="col text-center">
						<div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
							<span class="sr-only mx-auto">Loading...</span>
						</div>
					</div>
				</div>
				<div class="modal-body form-group">
					<input type="hidden" name="userId" id="userId">
					<div class="row">
						<div class="col">
							<label for="name">Nome *</label>
							<input id="name" name="name" class="form-control" type="text" placeholder="Nome">
						</div>
					</div>
					<div class="row">
						<div class="col">
							<label for="email">E-mail *</label>
							<input id="email" name="email" class="form-control" type="email"
							       placeholder="E-mail">
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<label for="type">Nível *</label>
							<select id="type" name="type" class="form-control form-select">
								<option value="">Selecionar</option>
								<option value="1">Admin</option>
								<option value="2">Convencional</option>
							</select>
						</div>
						<div class="col-md-6" id="passwordDiv">
							<label for="password">Senha *</label>
							<input id="password" name="password" class="form-control" type="text"
							       placeholder="Senha">
							<span class="f-12 text-muted m-l-5">Mínimo 8 caracteres</span>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4" id="activeDiv">
							<label for="active">Status</label>
							<select id="active" name="active" class="form-control form-select">
								<option value="1">Ativo</option>
								<option value="0">Inativo</option>
							</select>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<div class="col text-end">
						<button type="submit" class="btn btn-primary">Salvar Usuário</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="<?= BASEURL ?>assets/functions/user.js?v=<?= time() ?>"></script>