<div class="row">
    <div class="col">
        <div class="card p-3 m-2">
            <form id="filter" autocomplete="off">
                <div class="row">
                    <div class="col-md-2">
                        <a class="btn btn-primary text-white" href="#" onclick="openModal()"><i
                                    class="fa fa-plus"></i> Usuário</a>
                    </div>
                    <div class="col-md-4 my-auto">
                        <div class="form-group mt-2">
                            <input class="form-control" id="nameFilter" name="name" type="text" placeholder="Nome">
                        </div>
                    </div>
                    <div class="col-md-3 my-auto">
                        <div class="form-group mt-2">
                            <select name="type" id="typeFilter" class="form-control form-select">
                                <option value="-1">Selecione o Tipo</option>
                                <option value="1">Admin</option>
                                <option value="2">Consultor</option>
                                <option value="3">Empresa</option>
                            </select>
                        </div>
                    </div>
                    <div class="col text-end">
                        <button class="btn btn-danger" type="reset" onclick="resetTable()">Limpar</button>
                        <button class="btn btn-primary" type="submit">Buscar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card p-3 m-2">
            <div class="row">
                <div class="col">
                    <p>Exibindo <span id="partial"></span> de <span id="total"></span></p>
                </div>
            </div>
            <div class="row table-responsive-lg">
                <div class="col">
                    <table class="table table-hover table-sm" id="usersTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th class="text-center">Nome</th>
                            <th class="text-center">Tipo</th>
                            <th class="text-center">E-mail</th>
                            <th class="text-center">Status</th>
                            <th class="text-center">Ações</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal Cadastro-->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="subscriptionModal"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="addUser" method="post" autocomplete="off">
                <div class="modal-header">
                    <h5 class="modal-title">Registro de Usuário</h5>
                    <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="row mt-3">
                    <div class="col text-center">
                        <div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;" role="status">
                            <span class="sr-only mx-auto">Loading...</span>
                        </div>
                    </div>
                </div>
                <div class="modal-body form-group">
                    <input type="hidden" name="userId" id="userIdEdit">
                    <div class="row">
                        <div class="col">
                            <label for="nameEdit">Nome</label>
                            <input id="nameEdit" name="name" class="form-control" type="text" placeholder="Nome">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="emailEdit">E-mail</label>
                            <input id="emailEdit" name="email" class="form-control" type="email" placeholder="E-mail">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for="typeEdit">Tipo</label>
                            <select id="typeEdit" name="type" class="form-control form-select">
                                <option value="-1">Selecione</option>
                                <option value="1">Admin</option>
                                <option value="2">Consultor</option>
                                <option value="3">Empresa</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8" id="passwordEditDiv">
                            <label for="passwordEdit">Senha</label>
                            <input id="passwordEdit" name="password" class="form-control" type="text"
                                   placeholder="Senha">
                            <span style="font-size: 8px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                        </div>
                        <div class="col-md-4" id="activeEditDiv">
                            <label for="activeEdit">Status</label>
                            <select id="activeEdit" name="active" class="form-control form-select">
                                <option value="1">Ativo</option>
                                <option value="0">Inativo</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col text-end">
                        <button type="submit" class="btn btn-primary">Salvar Usuário</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


<script>

    var index = 0;
    var partial = 0;
    var total = 1;
    var name = 0;
    var type = -1;

    function openModal() {
        document.getElementById('passwordEditDiv').style.display = 'block';
        document.getElementById('activeEditDiv').style.display = 'block';
        $('#modal').modal('show');
        document.getElementById('addUser').reset();
    }

    function openModalEdit(id) {
        document.getElementById('passwordEditDiv').style.display = 'none';
        document.getElementById('activeEditDiv').style.display = 'none';
        document.getElementById('addUser').reset();
        $('.modal-body').css('opacity', .2);
        $('#modal').modal('show');
        if (id > 0) {
            startLoading();
            fetch(`<?= BASEURL ?>api/usuarios/${id}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    json = json.message[0];
                    setTimeout(function () {
                        $('.loaderTop').hide();
                        $('.form-group').css('opacity', 1);
                        $('.btn').attr('disabled', false);
                    }, 500);
                    document.getElementById('emailEdit').value = json.email;
                    document.getElementById('userIdEdit').value = json.id;
                    document.getElementById('typeEdit').value = json.type;
                    document.getElementById('nameEdit').value = json.name;
                    document.getElementById('activeEdit').value = json.active;
                    document.getElementById('passwordEdit').value = json.password;
                });
            });
        }
    }

    const formAddUser = document.getElementById('addUser');

    formAddUser.addEventListener('submit', e => {
        e.preventDefault();
        startLoading();
        let formData = formDataToJson('addUser');
        fetch("<?= BASEURL ?>usuarios/registrar", {
            method: 'POST',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(formData)
        }).then(response => {
            setTimeout(function () {
                $('.loaderTop').hide();
                $('.form-group').css('opacity', 1);
                $('.btn').attr('disabled', false);
            }, 500);
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                 $('#teste').show(200);
                if (response.status === 200) {
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    formAddUser.reset();
                    setTimeout(function () {
                        total = 1;
                        partial = index = name = 0;
                        type = -1;
                        $('#modal').modal('hide');
                        $("#usersTable tbody").empty();
                         $('#teste').hide(200);
                        generateTable();
                    }, 2000);
                } else {
                    setTimeout(function () {
                         $('#teste').hide(200);
                    }, 2000);
                }
            });
        });
    });

    const form = document.getElementById('filter');

    form.addEventListener('submit', e => {
        e.preventDefault();
        let formData = formDataToJson('filter');
        partial = 0;
        index = 0;
        total = 1;
        name = formData.name;
        type = formData.type;
        $("#usersTable tbody").empty();
        generateTable();
    });

    function resetTable() {
        index = 0;
        partial = 0;
        total = 1;
        name = 0;
        type = -1;
        $("#usersTable tbody").empty();
        generateTable();
    }

    function generateUsersTable(user) {
        let actions = '';
        actions += `<i class="fa fa-pencil text-info pointer" title="Editar" onclick="openModalEdit(${user.id})"></i> `;
        actions = `<td class="text-center">${actions} </td>`;
        return `<tr>
                    <td class="text-center">${user.name}</td>
                    <td class="text-center">${typeStr(user.type)}</td>
                    <td class="text-center">${user.email}</td>
                    <td class="text-center">${buttonStatus(user.active, user.id)}</td>
                    ${actions}
                </tr>`;
    }

    function buttonStatus(status, id) {
        if (status == 1) {
            return `
            <a class="btn btn-sm btn-success text-white" onclick="chanceStatusUser(${id}, 0)">
                Ativo
            </a>
            `;
        } else if (status == 0) {
            return `
            <a class="btn btn-sm btn-danger text-white" onclick="chanceStatusUser(${id}, 1)">
                Inativo
            </a>
            `;
        }
    }

    function chanceStatusUser(id, status) {
        fetch(`<?= BASEURL ?>usuarios/novo-status/?id=${id}&status=${status}`, {
            method: 'GET',
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            }
        }).then(response => {
            divMessage.classList.add("alert-danger");
            divMessage.classList.remove("alert-success");
            response.json().then(json => {
                divMessage.textContent = json.message;
                 $('#teste').show(200);
                if (response.status === 200) {
                    divMessage.classList.add("alert-success");
                    divMessage.classList.remove("alert-danger");
                    setTimeout(function () {
                        resetTable();
                         $('#teste').hide(200);
                    }, 2000);
                } else {
                    setTimeout(function () {
                         $('#teste').hide(200);
                    }, 2000);
                }
            });
        });
    }

    function typeStr(type) {
        if (type == 1) {
            return 'Admin';
        } else if (type == 2) {
            return 'Consultor';
        } else if (type == 3) {
            return 'Empresa';
        } else {
            return 'Desconhecido';
        }
    }

    function generateTable() {
        if (total > partial) {
            fetch(`<?= BASEURL ?>api/usuarios/?index=${index}&name=${name}&type=${type}`, {
                method: "GET",
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'
                }
            }).then(response => {
                response.json().then(json => {
                    $('#total').text(json.total);
                    $('#partial').text(json.partial);
                    total = json.total;
                    partial = json.partial;
                    let options = json.message.map(generateUsersTable);
                    $("#usersTable tbody").append(options);
                });
            });
        }
    }

    $(document).ready(function () {
        showLoading();
        generateTable();
        $(window).scroll(function (e) {
            if ($(window).scrollTop() + $(window).height() >= $(document).height() - 1) {
                e.preventDefault();
                e.stopPropagation();
                index++;
                generateTable();
            }
        });
        closeLoading();
    });

</script>
