<div class="page-body">
    <!-- Container-fluid starts-->
    <div class="container-fluid m-t-20">
        <div class="edit-profile">
            <div class="row">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-header pb-0">
                            <h4 class="card-title mb-0">Meu Perfil</h4>
                        </div>
                        <div class="card-body">
                            <div class="row mb-2">
                                <div class="profile-title">
                                    <div class="media" style="display: flex">
                                        <img class="img-70 rounded-circle" alt=""
                                             src="<?= BASEURL ?>uploads/<?= $user->getImg() ?>">
                                        <div class="media-body">
                                            <h3 class="mb-1 f-20 txt-primary m-l-20"><?= $user->getName() ?></h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col text-center">
                                    <div class="spinner-border loaderTop" style="width: 5rem; height: 5rem;"
                                         role="status">
                                        <span class="sr-only mx-auto">Loading...</span>
                                    </div>
                                </div>
                            </div>
                            <form autocomplete="off" id="editUser" class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="mb-3">
                                            <label for="password">Senha Atual *</label>
                                            <input id="password" name="password"
                                                   placeholder="Senha Atual" class="form-control" type="password">
                                        </div>
                                        <div class="mb-3">
                                            <label for="email">Email de Acesso *</label>
                                            <input name="email" id="email" class="form-control" type="email"
                                                   placeholder="Email de Acesso" value="<?= $user->getEmail() ?>">
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="mb-3">
                                            <label for="name">Nome *</label>
                                            <input id="name" name="name" value="<?= $user->getName() ?>"
                                                   class="form-control" type="text">
                                        </div>
                                        <div class="mb-3">
                                            <label>Imagem de Perfil</label><br>
                                            <span class="fileselector">
                                                    <label class="btn btn-block btn-danger text-white"
                                                           style="margin-top: 0"
                                                           for="imgUser">
                                                          <input class="upload-file-selector" id="imgUser" type="file"
                                                                 name="imgUser" style="height: 0">
                                                          <i class="fa fa-paperclip margin-correction"></i>
                                                              <span id="imgUserLabel"
                                                                    default="Anexar Arquivo">Anexar Arquivo</span>
                                                      </label>
                                                </span>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div>
                                            <label for="newPassword">Nova Senha *</label>
                                            <input id="newPassword" name="newPassword" class="form-control"
                                                   type="password" placeholder="Senha">
                                            <span style="font-size: 10px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                                        </div>
                                        <div class="mb-3">
                                            <label for="newPassword2">Confirmar Nova Senha *</label>
                                            <input id="newPassword2" name="newPassword2" class="form-control"
                                                   type="password" placeholder="Confirmar Nova Senha">
                                            <span style="font-size: 10px; color: grey; margin-left: 5px">Mínimo 8 caracteres</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-footer text-end">
                                    <button class="btn btn-primary btn-block" type="submit">Salvar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {
        $("#cnpj").keyup(function () {
            loadData();
        });
        $('input:file').change(function (e) {
            let input = e.target;

            if (input.files.length > 0) {
                input.parentElement.classList.remove('btn-primary');
                input.parentElement.classList.remove('btn-danger');
                input.parentElement.classList.add('btn-success');
                input.text = input.value;
                let string = input.value.replace('fakepath', '');

                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = string.slice(4);
            } else {
                input.parentElement.classList.remove('btn-success');
                input.parentElement.classList.add('btn-danger');
                let labelId = input.getAttribute('id') + 'Label';
                document.getElementById(labelId).textContent = document.getElementById(labelId).getAttribute('default');
            }
        });
    });

    const form = document.getElementById('editUser');

    function validateFormUser() {
        $('.form-control').removeClass('is-invalid is-valid');
        let errors = [];
        let ids = [];
        let radios = [];
        let classes = [];
        let greens = [];
        const formData = formDataToJson('editUser');

        if (formData.password.trim() == '') {
            errors.push('<b> Senha Atual</b>');
            ids.push('password');
        } else {
            greens.push('password')
        }
        if (formData.email.trim() == '') {
            errors.push('<b> Email de Acesso</b>');
            ids.push('email');
        } else {
            greens.push('email')
        }
        if (formData.name.trim() == '') {
            errors.push('<b> Nome</b>');
            ids.push('name');
        } else {
            greens.push('name')
        }
        if (formData.newPassword.trim() == '') {
            errors.push('<b> Nova Senha</b>');
            ids.push('newPassword');
        } else {
            greens.push('newPassword')
        }
        if (formData.newPassword2.trim() == '') {
            errors.push('<b> Confirmar Nova Senha</b>');
            ids.push('newPassword2');
        } else {
            greens.push('newPassword2')
        }

        for (let i = 0; i < greens.length; i++) {
            $('#' + greens[i]).addClass('is-valid')
        }

        if (formData.newPassword.trim() != '' && formData.newPassword2.trim() != '' && (formData.newPassword.length < 8 || formData.newPassword2.length < 8)) {
            showNotify('danger', 'As senhas devem ter no mínimo oito caracteres!', 1500);
            $('#newPassword, #newPassword2').addClass('is-invalid');
            return false;
        }

        if (formData.newPassword.trim() != '' && formData.newPassword2.trim() != '' && formData.newPassword != formData.newPassword2) {
            showNotify('danger', 'As senha estão diferentes!', 1500);
            $('#newPassword, #newPassword2').addClass('is-invalid');
            return false;
        }

        return verifyMessage(errors, ids, radios, classes);
    }

    form.addEventListener('submit', e => {
        e.preventDefault();
        startLoading();
        if (!validateFormUser()) {
            setTimeout(function () {
                $('.loaderTop').hide();
                $('.form-group').css('opacity', 1);
                $('.btn').attr('disabled', false);
            }, 500);
            return;
        }
        let method = 'POST';
        let formData = formDataToJson('editUser');
        fetch(`${baseurl}usuarios/editar`, {
            method: method,
            credentials: 'same-origin',
            headers: {
                'Accept': 'application/json',
            },
            body: new FormData(form)
        }).then(response => {
            setTimeout(function () {
                $('.loaderTop').hide();
                $('.form-group').css('opacity', 1);
                $('.btn').attr('disabled', false);
            }, 500);
            response.json().then(json => {
                if (response.status === 200) {
                    showNotify('success', json.message, 2000);
                    form.reset();
                    setTimeout(function () {
                        location.reload();
                    }, 2000);
                } else {
                    showNotify('danger', json.message, 2000);
                }
            });
        });
    });

</script>